### ISSUE TITLE
Plugins processes not cleaned up, possibly only when errors occur

### ISSUE THREAD

**Issue by scottyw** [lyraproj/lyra#134] opened 2019-02-19 17:51 UTC
**Describe the bug**
Lyra is not cleaning up plugin processes on all occasions and I am finding this sort of thing in my process list:

```
  501 81143     1   0 11Feb19 ??         0:00.02 /System/Library/PrivateFrameworks/KerberosHelper/Helpers/DiskUnmountWatcher
  501 83702     1   0  4Feb19 ??         0:21.65 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build751753963/b001/exe/main --debug plugin example
  501 83703     1   0  4Feb19 ??         0:23.97 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build751753963/b001/exe/main --debug plugin identity
  501 83704     1   0  4Feb19 ??         0:24.55 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build751753963/b001/exe/main --debug plugin aws
  501 83705     1   0  4Feb19 ??         1:02.73 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build751753963/b001/exe/main --debug plugin tfaws
  501 83708     1   0  4Feb19 ??         0:38.76 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build751753963/b001/exe/main --debug plugin tfkubernetes
  501 87235     1   0  4Feb19 ??         0:23.31 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build695187835/b001/exe/main --debug plugin example
  501 87236     1   0  4Feb19 ??         0:24.09 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build695187835/b001/exe/main --debug plugin identity
  501 87237     1   0  4Feb19 ??         0:25.16 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build695187835/b001/exe/main --debug plugin aws
  501 87238     1   0  4Feb19 ??         1:03.76 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build695187835/b001/exe/main --debug plugin tfaws
  501 87242     1   0  4Feb19 ??         0:39.54 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build695187835/b001/exe/main --debug plugin tfkubernetes
  501 87982     1   0  4Feb19 ??         0:23.01 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build002614375/b001/exe/main --debug plugin example
  501 87983     1   0  4Feb19 ??         0:22.48 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build002614375/b001/exe/main --debug plugin identity
  501 87984     1   0  4Feb19 ??         0:25.68 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build002614375/b001/exe/main --debug plugin aws
  501 87987     1   0  4Feb19 ??         0:38.82 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build002614375/b001/exe/main --debug plugin tfkubernetes
  501 87989     1   0  4Feb19 ??         1:45.03 /var/folders/26/7dm8dk111n1109jy0p7t0wgr0000gn/T/go-build002614375/b001/exe/main --debug plugin puppet
```

It might only be in the case that the run fails.

**To Reproduce**
Not sure, but I have recently been testing both plugins that panic and have had plenty of badly formed workflows, so could be at either stage of the run.

**Expected behavior**
No plugin processes left alive once Lyra exits.

**Comment by thallgren** [comment] 2019-03-16 14:44
I think this is a duplicate of #179, for which I have a solution in https://github.com/lyraproj/wfe/pull/16.

**Comment by thallgren** [comment] 2019-03-19 14:48
Should be solved by lyraproj/wfe#16

**Comment by scottyw** [comment] 2019-03-29 10:13
Looks like this has cropped up again.

I'm seeing many plugins running after failed Lyra runs:
```
  501 42458     1   0 13Mar19 ??         0:00.27 build/goplugin-example
  501 42459     1   0 13Mar19 ??         0:00.27 build/goplugin-identity
  501 42460     1   0 13Mar19 ??         0:00.26 build/goplugin-puppetdsl
  501 42461     1   0 13Mar19 ??         1:20.24 build/goplugin-tf-aws
  501 42463     1   0 13Mar19 ??         0:46.19 build/goplugin-tf-azurerm
  501 42464     1   0 13Mar19 ??         0:10.92 build/goplugin-tf-github
  501 42465     1   0 13Mar19 ??         0:39.67 build/goplugin-tf-google
  501 42466     1   0 13Mar19 ??         0:42.05 build/goplugin-tf-kubernetes
  501 42500     1   0 13Mar19 ??         0:11.81 build/goplugin-aws
  501 42501     1   0 13Mar19 ??         0:00.25 build/goplugin-example
  501 42502     1   0 13Mar19 ??         0:00.25 build/goplugin-identity
  501 42503     1   0 13Mar19 ??         0:00.25 build/goplugin-puppetdsl
  501 42504     1   0 13Mar19 ??         1:20.37 build/goplugin-tf-aws
```

That's also our suspect for this identity service problem:
```
2019-03-28T18:44:08.487Z [DEBUG] lyra.identity: 2019-03-28T18:44:08.487Z [ERROR] Invoke failed: error="Go function GetExternal returned error 'timeout' (file: /Users/scott/go/pkg/mod/github.com/lyraproj/pcore@v0.0.0-20190320221415-6e1d1bd9c47d/types/function.go, line: 104)"
2019-03-28T18:44:08.497Z [DEBUG] lyra: GetExternal: intId=lyra://puppet.com/aws_ts/aws_subnet1?hid=TerraformAws%3A%3AAws_subnet&rt=TerraformAws%3A%3AAws_subnet extId=<nil>
2019-03-28T18:44:08.499Z [DEBUG] lyra: Create state: intId=lyra://puppet.com/aws_ts/aws_subnet1?hid=TerraformAws%3A%3AAws_subnet&rt=TerraformAws%3A%3AAws_subnet
```
which leads to:
```
invocation of Identity::Service getExternal failed: PCORE_GO_FUNCTION_ERROR Go function GetExternal returned error 'timeout' (file: /Users/scott/go/pkg/mod/github.com/lyraproj/pcore@v0.0.0-20190320221415-6e1d1bd9c47d/types/function.go, line: 104)
 at /Users/scott/go/pkg/mod/github.com/lyraproj/servicesdk@v0.0.0-20190320113120-6be298b18bf0/grpc/client.go:63 (github.com/lyraproj/servicesdk/grpc.(*Client).Invoke)
 at /Users/scott/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190321125752-37a17f3018a7/service/identity.go:33 (github.com/lyraproj/wfe/service.(*identity).getExternal)
 at /Users/scott/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190321125752-37a17f3018a7/service/crud.go:64 (github.com/lyraproj/wfe/service.ApplyState)
 at /Users/scott/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190321125752-37a17f3018a7/wfe/resource.go:64 (github.com/lyraproj/wfe/wfe.(*resource).Run)
 at /Users/scott/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190321125752-37a17f3018a7/wfe/workflowengine.go:453 (github.com/lyraproj/wfe/wfe.(*workflowEngine).runActivity)
 at /Users/scott/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190321125752-37a17f3018a7/wfe/workflowengine.go:403 (github.com/lyraproj/wfe/wfe.(*workflowEngine).activityWorker)
 at /Users/scott/go/pkg/mod/github.com/lyraproj/wfe@v0.0.0-20190321125752-37a17f3018a7/wfe/workflowengine.go:319 (github.com/lyraproj/wfe/wfe.(*workflowEngine).Run.func2)
 at /Users/scott/go/pkg/mod/github.com/lyraproj/pcore@v0.0.0-20190320221415-6e1d1bd9c47d/px/context.go:165 (github.com/lyraproj/pcore/px.Fork.func1)
2019-03-28T18:44:10.583Z [DEBUG] lyra: plugin process exited: path=build/goplugins/identity pid=5950
2019-03-28T18:44:10.583Z [DEBUG] lyra: plugin exited
```

**Comment by thallgren** [comment] 2019-04-11 09:03
@scottyw could the lingering processes be the result of killing lyra with kill or Ctrl-C? If so, this would be fixed by #221. If not, the please provide more info about in what situations the processes refuse to die.

**Comment by thallgren** [comment] 2019-04-11 14:44
One thing that I just notices is that the `lyra generate` starts all the plugins but the just forgets to kill them. I'll fix that.

**Closed** 2019-04-12 12:59 UTC
Labels: Type: Bug

**Comment by scottyw** [comment] 2019-04-12 13:06
I'm not using ctrl-C, just seeing the run panic due to (expected) workflow failures. I'll keep an eye on master now and check it's all grand.

**Comment by thallgren** [comment] 2019-04-12 13:11
@scottyw please note that a "make all" would also leave plugin processes dangling due to #230.

**Comment by scottyw** [comment] 2019-04-12 13:13
Oh of course. That's not ideal.
